[package]
name = "rosettaboy-rs"
version = "0.1.0"
authors = ["Shish <shish@shishnet.org>"]
edition = "2018"

[dependencies]
sdl2 = "0.32"
num_enum = "0.4.2"
structopt = "*"
bitflags = "*"
packed_struct = "*"
packed_struct_codegen = "*"
