name: C++

on:
  push:
    paths:
    - 'cpp/**'
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y clang-format-10
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check
      working-directory: cpp
      run: clang-format-10 --version && clang-format-10 $(find src -type f | grep -v args.h) --dry-run --ferror-limit 10 -Werror
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y gcc cmake libsdl2-dev
    - name: Checkout
      uses: actions/checkout@v2
    - name: CMake
      working-directory: cpp
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: Build
      working-directory: cpp
      run: make
    - name: CPU Integration Tests
      run: ./gblargh.py cpp
    - name: Benchmark
      run: |
        cd cpp
        wget https://github.com/sjl/cl-gameboy/blob/master/roms/opus5.gb?raw=true -O opus5.gb
        ./run.sh --silent --headless --profile 600 --turbo opus5.gb
