name: C++

on:
  push:
    paths:
    - 'cpp/**'
    - '.github/workflows/cpp.yml'
  pull_request:
    paths:
    - 'cpp/**'
    - '.github/workflows/cpp.yml'
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-22.04
    steps:
    - name: Install Deps
      run: which clang-format-14 || (sudo apt-get update && sudo apt-get install -y clang-format-14)
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check
      working-directory: cpp
      run: ./format.sh && git diff --exit-code
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y gcc cmake libsdl2-dev
    - name: Checkout
      uses: actions/checkout@v3
    - name: CMake
      working-directory: cpp
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: Build
      working-directory: cpp
      run: make
    - name: CPU Integration Tests
      run: ./blargg.py cpp
    - name: Benchmark
      working-directory: cpp
      run: |
        wget https://github.com/sjl/cl-gameboy/blob/master/roms/opus5.gb?raw=true -O opus5.gb
        ./run.sh --silent --headless --profile 600 --turbo opus5.gb
