name: Go

on:
  push:
    paths:
    - 'go/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y golang libsdl2-dev
    - name: Install go deps
      run: go get github.com/veandco/go-sdl2/sdl
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      working-directory: go
      run: go build -o rosettaboy-go src/*.go
    - name: CPU Integration Tests
      run: ./gblargh.py go
    - name: Benchmark
      run: |
        cd go
        wget https://github.com/sjl/cl-gameboy/blob/master/roms/opus5.gb?raw=true -O opus5.gb
        ./run.sh --silent --headless --profile 600 --turbo opus5.gb
