name: Go

on:
  push:
    paths:
    - 'go/**'
    - '.github/workflows/go.yml'
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-20.04
    steps:
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y golang libsdl2-dev
    - name: Set Up Toolchain Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go
        key: ${{ runner.os }}-go-toolchain
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y golang libsdl2-dev
    - name: Set Up Toolchain Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go
        key: ${{ runner.os }}-go-toolchain
    - name: Install Go Deps
      run: go get github.com/veandco/go-sdl2/sdl
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Up Build Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gocode
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
    - name: Build
      working-directory: go
      run: go build -o rosettaboy-go src/*.go
    - name: CPU Integration Tests
      run: ./blargg.py go
    - name: Benchmark
      working-directory: go
      run: |
        wget https://github.com/sjl/cl-gameboy/blob/master/roms/opus5.gb?raw=true -O opus5.gb
        ./run.sh --silent --headless --profile 600 --turbo opus5.gb
