name: Go

on:
  push:
    branches:
    - master
    paths:
    - 'go/**'
    - '.github/workflows/go.yml'
  pull_request:
    paths:
    - 'go/**'
    - '.github/workflows/go.yml'
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-22.04
    steps:
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y golang libsdl2-dev
    - name: Set Up Toolchain Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go
        key: ${{ runner.os }}-go-toolchain
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check
      working-directory: go
      run: ./format.sh && git diff --exit-code
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y golang libsdl2-dev
    - name: Set Up Toolchain Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go
        key: ${{ runner.os }}-go-toolchain
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Up Build Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gocode
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
    - name: Build
      working-directory: go
      run: go build -o rosettaboy-go src/*.go
    - name: CPU Integration Tests
      run: ./utils/blargg.py go
    - name: Benchmark
      run: ./utils/bench.py go --default --frames 10
