name: Nim

on:
  push:
    branches:
    - master
    paths:
    - 'nim/**'
    - '.github/workflows/nim.yml'
  pull_request:
    paths:
    - 'nim/**'
    - '.github/workflows/nim.yml'
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-22.04
    steps:
    - name: Install Tools
      uses: jiro4989/setup-nim-action@v1
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check
      working-directory: nim
      run: ./format.sh && git diff --exit-code
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - name: Install Tools
      uses: jiro4989/setup-nim-action@v1
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      working-directory: nim
      run: nimble build -Y
#    - name: Test
#      working-directory: nim
#      run: nimble test -Y
    - name: CPU Integration Tests
      run: ./utils/blargg.py nim
    - name: Benchmark
      working-directory: nim
      run: |
        wget https://github.com/sjl/cl-gameboy/blob/master/roms/opus5.gb?raw=true -O opus5.gb
        ./run.sh --silent --headless --profile 600 --turbo opus5.gb
