name: PHP

on:
  push:
    paths:
    - 'php/**'
    - '.github/workflows/php.yml'
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-20.04
    steps:
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y php-cli
    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
        php composer-setup.php
        php -r "unlink('composer-setup.php');"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Deps
      working-directory: php
      run: ../composer.phar require friendsofphp/php-cs-fixer
    - name: Check
      working-directory: php
      run: vendor/bin/php-cs-fixer fix --dry-run
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y php-cli
    - name: Checkout
      uses: actions/checkout@v2
    - name: CPU Integration Tests
      run: ./gblargh.py php
    - name: Benchmark
      working-directory: php
      run: |
        wget https://github.com/sjl/cl-gameboy/blob/master/roms/opus5.gb?raw=true -O opus5.gb
        ./run.sh -S -H -p 600 -t opus5.gb
