name: PHP

on:
  push:
    branches:
    - master
    paths:
    - 'php/**'
    - '.github/workflows/php.yml'
  pull_request:
    paths:
    - 'php/**'
    - '.github/workflows/php.yml'
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-22.04
    steps:
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y php-cli
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php
        php -r "unlink('composer-setup.php');"
    - name: Install Deps
      working-directory: php
      run: ../composer.phar require friendsofphp/php-cs-fixer
    - name: Check
      working-directory: php
      run: ./format.sh && git diff --exit-code
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y php-cli
    - name: Checkout
      uses: actions/checkout@v3
    - name: CPU Integration Tests
      run: ./utils/blargg.py php
    - name: Benchmark
      working-directory: php
      run: |
        wget https://github.com/sjl/cl-gameboy/blob/master/roms/opus5.gb?raw=true -O opus5.gb
        ./run.sh -S -H -p 600 -t opus5.gb
