name: Python

on:
  push:
    paths:
    - 'py/**'
    - '.github/workflows/py.yml'
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check
      uses: rickstaa/action-black@v1
      with:
        black_args: "--check py/src"
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
    - name: Install Deps
      run: (python3 -m venv --help >/dev/null) || (sudo apt-get update && sudo apt-get install -y python3-venv)
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Up Build Cache
      uses: actions/cache@v2
      with:
        path: |
          venv
        key: ${{ runner.os }}-python
    - name: Setup Virtualenv
      run: python3 -m venv venv && ./venv/bin/pip install pysdl2 pysdl2-dll
    - name: CPU Integration Tests
      run: ./blargg.py py
    - name: Benchmark
      working-directory: py
      run: |
        wget https://github.com/sjl/cl-gameboy/blob/master/roms/opus5.gb?raw=true -O opus5.gb
        ./run.sh --silent --headless --profile 600 --turbo opus5.gb
