name: Rust

on:
  push:
    paths:
    - 'rs/**'
    - '.github/workflows/rs.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y gcc libsdl2-dev cargo
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Up Build Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          rs/target
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      working-directory: rs
      run: cargo build --release
    - name: CPU Integration Tests
      run: ./gblargh.py rs
    - name: Benchmark
      run: |
        cd rs
        wget https://github.com/sjl/cl-gameboy/blob/master/roms/opus5.gb?raw=true -O opus5.gb
        ./run.sh --silent --headless --profile 600 --turbo opus5.gb
