name: Rust

on:
  push:
    paths:
    - 'rs/**'
    - '.github/workflows/rs.yml'
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-22.04
    steps:
    - name: Set Up Toolchain Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.rustup/toolchains
          ~/.rustup/update-hashes
          ~/.rustup/settings.toml
        key: ${{ runner.os }}-rust-toolchain
    - name: Set Up Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check
      working-directory: rs
      run: ./format.sh && git diff --exit-code
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y gcc libsdl2-dev cargo
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Up Build Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          rs/target
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      working-directory: rs
      run: cargo build --release
    - name: CPU Integration Tests
      run: ./blargg.py rs
    - name: Benchmark
      working-directory: rs
      run: |
        wget https://github.com/sjl/cl-gameboy/blob/master/roms/opus5.gb?raw=true -O opus5.gb
        ./run.sh --silent --headless --profile 600 --turbo opus5.gb
