name: Utils

on:
  push:
    branches:
    - master
    paths:
    - 'utils/**'
    - '.github/workflows/utils.yml'
  pull_request:
    paths:
    - 'utils/**'
    - '.github/workflows/utils.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: Build
      working-directory: utils
      run: docker build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) -t rosettaboy .
    - name: Run
      run: ./utils/shell.sh ./utils/bench.py --default --frames 10
